#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export XKL_XMODMAP_DISABLE=1

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

# Start dbus
dbus-launch --exit-with-session

# Start accessibility services
/usr/lib/at-spi2-core/at-spi-bus-launcher --launch-immediately &

vncconfig -iconic &
startxfce4 &
